# Generated by Django 5.1.1 on 2025-12-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_price',
            new_name='price',
        ),
    ]
